HTTP/2 Transport Support
wso2/carbon-transports pull request #169
Opened 2017-02-09 20:46 UTC by warunalakshitha

HTTP/2
HTTP/2 is introduced to address some drawbacks of HTTP/1 versions with features of Binary information exchange, compressed headers,multiplexing, Server Push .

Implementation
This pull request contains the initial implementation required to support HTTP/2 for current HTTP server connector including following.

Netty upgrade to 4.1.x (Required for HTTP/2)
HTTP/2 and HTTP/2 over TLS support
HTTP/2 multiplexing

2017-02-12 04:35 UTC, Kishanthan requested changes

2017-02-12 04:35 UTC, Kishanthan commented on http/org.wso2.carbon.transport.http.netty/src/main/java/org/wso2/carbon/transport/http/netty/listener/HTTPServerChannelInitializer.java
> +            if (AsciiString.contentEquals(Http2CodecUtil.HTTP_UPGRADE_PROTOCOL_NAME, protocol)) {
inverse this if and return early for negative case

2017-02-12 04:35 UTC, Kishanthan commented on http/org.wso2.carbon.transport.http.netty/src/main/java/org/wso2/carbon/transport/http/netty/listener/http2/HTTP2ResponseCallback.java
> +
Unnecessary new line. please remove it.

2017-02-12 04:35 UTC, Kishanthan commented on http/org.wso2.carbon.transport.http.netty/src/main/java/org/wso2/carbon/transport/http/netty/listener/http2/HTTP2ResponseCallback.java
> +
Unnecessary new line. please remove it.

2017-02-12 04:35 UTC, Kishanthan commented on http/org.wso2.carbon.transport.http.netty/src/main/java/org/wso2/carbon/transport/http/netty/listener/http2/HTTP2SourceHandler.java
> +
Unnecessary new line. please remove it.

2017-02-12 04:44 UTC, Kishanthan requested changes

2017-02-12 04:44 UTC, Kishanthan commented on http/org.wso2.carbon.transport.http.netty/src/main/java/org/wso2/carbon/transport/http/netty/listener/http2/HTTP2ResponseCallback.java
> +
Unnecessary new line. please remove it.

2017-02-12 04:44 UTC, Kishanthan commented on http/org.wso2.carbon.transport.http.netty/src/main/java/org/wso2/carbon/transport/http/netty/listener/http2/HTTP2ResponseCallback.java
> +                // HTTP2 Header Request response
Best practice is to place the comment at the end of else if { // comment

2017-02-12 19:37 UTC, warunalakshitha commented on http/org.wso2.carbon.transport.http.netty/src/main/java/org/wso2/carbon/transport/http/netty/listener/HTTPServerChannelInitializer.java
> +            if (AsciiString.contentEquals(Http2CodecUtil.HTTP_UPGRADE_PROTOCOL_NAME, protocol)) {
there can be multiple upgrade protocols. So if we return then that logic will break

2017-02-12 20:08 UTC, warunalakshitha commented on http/org.wso2.carbon.transport.http.netty/src/main/java/org/wso2/carbon/transport/http/netty/listener/HTTPServerChannelInitializer.java
> +            if (AsciiString.contentEquals(Http2CodecUtil.HTTP_UPGRADE_PROTOCOL_NAME, protocol)) {
Other issues fixed in https://github.com/wso2/carbon-transports/pull/172

2017-02-13 08:19 UTC, Kishanthan commented
We can close this as the same will be addressed in #172

2017-02-13 08:19 UTC, closed without merging