[File Server Connector] bug fixes
wso2/carbon-transports pull request #199
Opened 2017-02-17 13:32 UTC by dilini-muthumala

- Addressing https://github.com/ballerinalang/ballerina/issues/1947 by deleting the file by default, if the message processor did not ack.
- Addressing https://github.com/ballerinalang/ballerina/issues/1949 by giving a warning in case user provides an invaid value to  `fileSortAttribute` parameter.

2017-02-18 09:20 UTC, dilini-muthumala commented
https://github.com/wso2/carbon-transports/pull/199/commits/8e46c726f3896ba063baa78e533ce6b71ee6cd05 contains the fix for the error log getting printed when running integration tests: `Error occurred when trying to get input stream from file at URI`

2017-02-19 08:13 UTC, Kishanthan requested changes
Please send this to "transport-stabilize" branch

2017-02-19 08:23 UTC, dilini-muthumala commented
@Kishanthan Changed the base of the PR to transport-stabilize.

2017-02-19 11:04 UTC, Kishanthan approved these changes

2017-02-19 11:04 UTC, merged