Test Cases for WebSocket
wso2/carbon-transports pull request #223
Opened 2017-02-23 05:42 UTC by irunika

resolves #222

2017-02-23 18:07 UTC, Kishanthan requested changes
Please send this PR to https://github.com/wso2/carbon-transports/tree/server-connector-bug-fixes branch

2017-02-23 18:23 UTC, Kishanthan requested changes

2017-02-23 18:23 UTC, Kishanthan commented on http/org.wso2.carbon.transport.http.netty/src/test/java/org/wso2/carbon/transport/http/netty/websocket/WebSocketMessageProcessor.java
> +            public void run() {
This method logic looks too long, can we break this into separate methods?

2017-02-23 18:23 UTC, Kishanthan commented on http/org.wso2.carbon.transport.http.netty/src/test/java/org/wso2/carbon/transport/http/netty/websocket/WebSocketTestCases.java
> +        Thread.sleep(3000);
Please explain the need for thread sleep in all the cases?

2017-02-23 18:23 UTC, Kishanthan commented on http/org.wso2.carbon.transport.http.netty/src/test/java/org/wso2/carbon/transport/http/netty/util/clients/http2/HTTP2ClientInitializer.java
> +package org.wso2.carbon.transport.http.netty.util.clients.http2;
Any particular reason for the package rename ? As a best practice, we don't use plural in package names

2017-02-23 18:23 UTC, Kishanthan commented on http/org.wso2.carbon.transport.http.netty/src/test/java/org/wso2/carbon/transport/http/netty/websocket/WebSocketTestCases.java
> +    private WebSocketClient secondaryClient = new WebSocketClient();
Explain the need for two clients for this test case

2017-02-23 21:01 UTC, irunika commented on http/org.wso2.carbon.transport.http.netty/src/test/java/org/wso2/carbon/transport/http/netty/util/clients/http2/HTTP2ClientInitializer.java
> +package org.wso2.carbon.transport.http.netty.util.clients.http2;
I will change it back then. Since there are can be many clients inside the package renamed the package.

2017-02-23 21:03 UTC, irunika commented on http/org.wso2.carbon.transport.http.netty/src/test/java/org/wso2/carbon/transport/http/netty/websocket/WebSocketTestCases.java
> +        Thread.sleep(3000);
Message delivery is asynchronous. This check whether the sent message has been pushed back from the server. So there is a small time given to ensure the message is received to the client handler.

2017-02-23 21:04 UTC, irunika commented on http/org.wso2.carbon.transport.http.netty/src/test/java/org/wso2/carbon/transport/http/netty/websocket/WebSocketTestCases.java
> +    private WebSocketClient secondaryClient = new WebSocketClient();
Primary client is the one who is checking the connections of the Server. When secondary server is connecting to the endpoint message will be sent to the primary client indicating the state of the secondary client.

2017-02-24 06:11 UTC, Kishanthan commented
Closing this as there is another PR - https://github.com/wso2/carbon-transports/pull/231

2017-02-24 06:11 UTC, closed without merging