File Server Connector Bug Fixes & Improvements
wso2/carbon-transports pull request #228
Opened 2017-02-23 14:41 UTC by dilini-muthumala

- Fixing https://github.com/ballerinalang/ballerina/issues/1949 by adding a warn log.
- With reference to https://github.com/ballerinalang/ballerina/issues/1947, adding `deleteIfNotAcknowledged` parameter.
- Fixing https://github.com/ballerinalang/ballerina/issues/2099

2017-02-23 18:06 UTC, Kishanthan requested changes
Please send this PR to https://github.com/wso2/carbon-transports/tree/server-connector-bug-fixes branch

2017-02-23 18:11 UTC, Kishanthan requested changes

2017-02-23 18:11 UTC, Kishanthan commented on file/org.wso2.carbon.transport.file/src/main/java/org/wso2/carbon/transport/file/connector/server/FileConsumer.java
> +            } catch (RuntimeException re) {
Why catching Runtime Exception here?

2017-02-23 18:11 UTC, Kishanthan commented on file/org.wso2.carbon.transport.file/src/main/java/org/wso2/carbon/transport/file/connector/server/FileConsumer.java
> +                if (strSortParam.equals(Constants.FILE_SORT_VALUE_NAME) && bSortOrderAscending) {
Can we use switch case for all these ?

2017-02-24 06:45 UTC, dilini-muthumala commented on file/org.wso2.carbon.transport.file/src/main/java/org/wso2/carbon/transport/file/connector/server/FileConsumer.java
> +            } catch (RuntimeException re) {
Removed it in https://github.com/wso2/carbon-transports/pull/228/commits/bd704ce1531f38c52ffc2b20070992a82323887d. I thought `Boolean.parseBoolean()` would throw a `RuntimeException` if the argument given is neither `true` nor `false`. I just looked at the implementation and it returns `false` for any argument other than `true` :(

2017-02-24 06:45 UTC, dilini-muthumala commented on file/org.wso2.carbon.transport.file/src/main/java/org/wso2/carbon/transport/file/connector/server/FileConsumer.java
> +                if (strSortParam.equals(Constants.FILE_SORT_VALUE_NAME) && bSortOrderAscending) {
+1. Done in https://github.com/wso2/carbon-transports/pull/228/commits/bd704ce1531f38c52ffc2b20070992a82323887d

2017-02-24 07:10 UTC, Kishanthan approved these changes

2017-02-24 07:10 UTC, merged