Bug fixes
wso2/carbon-transports pull request #233
Opened 2017-02-24 07:07 UTC by warunalakshitha

When doing load test some requests were failed due to thread blocking during channel flush. Currently we are using encoder directly to write to channel but it has encoder write method does not check whether the channel is in event loop. Using writer object this can be fix.

Connection Initiation handler executors does get fired during upgrade http/2 and http requests. Fixed with this pull request

2017-02-24 08:06 UTC, Kishanthan commented
We will add this for next minor release

2017-02-24 08:06 UTC, Kishanthan requested changes
We will add this for next minor release

2017-02-24 08:13 UTC, warunalakshitha commented
related to https://github.com/wso2/carbon-transports/issues/227

2017-03-03 10:18 UTC, Kishanthan commented
Please send this to transport stabilize branch.

2017-03-14 12:19 UTC, warunalakshitha commented
Sent new pr to transport stabilize branch hence closing this pr.
https://github.com/wso2/carbon-transports/pull/244

2017-03-14 12:19 UTC, closed without merging