Provide OSGi support for carbon-transport
wso2/carbon-transports pull request #238
Opened 2017-03-02 06:34 UTC by thusithathilina

Note that I've changed the carbon-messaging dependency version to 2.2.4. Before merging this PR please merge https://github.com/wso2/carbon-messaging/pull/59 and do a carbon-messaging release and then use that version with the carbon-transport

2017-03-03 10:15 UTC, Kishanthan requested changes

2017-03-03 10:15 UTC, Kishanthan commented on connector-framework/src/main/java/org/wso2/carbon/connector/framework/ConnectorManager.java
> +        if (DataHolder.getInstance().getBundleContext() != null) {
This will not work in a non-OSGi env as we are strictly checking for bundleContext availability and then calling initializeConnectors.

2017-03-03 10:17 UTC, Kishanthan commented
Also can you send this to trasnport stabilize branch?

2017-03-05 14:34 UTC, thusithathilina commented on connector-framework/src/main/java/org/wso2/carbon/connector/framework/ConnectorManager.java
> +        if (DataHolder.getInstance().getBundleContext() != null) {
Yes. That is intended. This will only work in OSGi environment

2017-05-02 17:28 UTC, Kishanthan approved these changes

2017-05-02 17:28 UTC, Kishanthan commented on connector-framework/src/main/java/org/wso2/carbon/connector/framework/ConnectorManager.java
> +        if (DataHolder.getInstance().getBundleContext() != null) {
Ok

2017-05-03 07:08 UTC, bsenduran approved these changes

2017-05-03 09:16 UTC, merged