Test Cases for WebSocket
wso2/carbon-transports pull request #267
Opened 2017-04-17 11:16 UTC by irunika

This PR resolves #222.
This has all necessary test cases to check current WebSocket server side capabilities.

2017-04-17 15:33 UTC, isudana requested changes

2017-04-17 15:33 UTC, isudana commented on http/org.wso2.carbon.transport.http.netty/src/main/java/org/wso2/carbon/transport/http/netty/common/Constants.java
> +    public static final String WEBSOCKET_PROTOCOL_NAME = "ws";
Can't we use the same constant WEBSOCKET_PROTOCOL

2017-04-17 15:33 UTC, isudana commented on http/org.wso2.carbon.transport.http.netty/src/main/java/org/wso2/carbon/transport/http/netty/listener/WebSocketSessionManager.java
> -/*
Why this is removed in a test case PR ?

2017-04-17 15:33 UTC, isudana commented on http/org.wso2.carbon.transport.http.netty/src/test/java/org/wso2/carbon/transport/http/netty/util/client/websocket/WebSocketClient.java
> +            throw new NullPointerException("Cannot find the channel to write");
we shouldn't thow a NPE

2017-04-17 15:33 UTC, isudana commented on http/org.wso2.carbon.transport.http.netty/src/test/java/org/wso2/carbon/transport/http/netty/util/client/websocket/WebSocketClient.java
> +            throw new NullPointerException("Cannot find the channel to write");
we shouldn't throw a NPE

2017-04-18 05:09 UTC, irunika commented on http/org.wso2.carbon.transport.http.netty/src/main/java/org/wso2/carbon/transport/http/netty/listener/WebSocketSessionManager.java
> -/*
This is a previously done change. If it is not appropriate to put it here I can send another PR for this.

2017-04-18 07:14 UTC, isudana requested changes

2017-04-18 07:14 UTC, isudana commented on http/org.wso2.carbon.transport.http.netty/src/test/java/org/wso2/carbon/transport/http/netty/util/client/websocket/WebSocketClient.java
> +            throw new IllegalArgumentException("Cannot find the channel to write");
Why IllegalArgumentException here and IOException in L165

2017-04-18 07:14 UTC, isudana commented on http/org.wso2.carbon.transport.http.netty/src/test/java/org/wso2/carbon/transport/http/netty/websocket/WebSocketTestCase.java
> +            assertTrue(false);
can we use fail() here or just throw it so that the test case will fail.

2017-04-18 08:43 UTC, irunika commented on http/org.wso2.carbon.transport.http.netty/src/test/java/org/wso2/carbon/transport/http/netty/util/client/websocket/WebSocketClient.java
> +            throw new IllegalArgumentException("Cannot find the channel to write");
It was mistake and thanks for pointing it out. IMHO it is better to use IllegalArgumentException for this and changed others to that.

2017-04-18 08:47 UTC, isudana approved these changes

2017-04-18 08:47 UTC, merged