Improvements for WebSocket Ping Pong support
wso2/carbon-transports pull request #408
Opened 2017-10-24 13:12 UTC by irunika

This PR includes improvements for WebSocket Ping Pong support with modifications of test cases.

2017-10-24 13:19 UTC, SupunS requested changes

2017-10-24 13:19 UTC, SupunS commented on http/org.wso2.carbon.transport.http.netty/src/test/java/org/wso2/carbon/transport/http/netty/websocket/WebSocketTestClientConnectorListener.java
> +        if ("ping".equals(textMessage.getText())) {
Better to make "ping" a constant. Fix in all places

2017-10-25 09:18 UTC, shafreenAnfar approved these changes

2017-10-25 09:50 UTC, SupunS approved these changes

2017-10-25 11:24 UTC, merged

2017-11-08 10:02 UTC, nuwanw commented on http/org.wso2.carbon.transport.http.netty/src/test/java/org/wso2/carbon/transport/http/netty/util/client/websocket/WebSocketClientHandler.java
>              logger.debug("WebSocket Client received  binary message: " + bufferReceived.toString());
better check whether debug is enabled when adding debug logs with string concatinavtion

2017-11-08 10:03 UTC, nuwanw commented on http/org.wso2.carbon.transport.http.netty/src/test/java/org/wso2/carbon/transport/http/netty/websocket/WebSocketClientTestCase.java
> +                    Assert.assertTrue(false, e.getMessage());
Assert.fail can be used instead of assertTrue